### ISSUE TITLE
Issues with CKAN 2.7

### ISSUE THREAD

**Issue by klikstermkd** [ckan/ckanext-archiver#50]
The extension calls a method https://github.com/ckan/ckanext-archiver/blob/master/ckanext/archiver/command_celery.py#L56 which is inherited from `CkanCommand` defined in `cli.py`, but that method in 2.7 is removed and now it's a standalone function https://github.com/ckan/ckan/blob/dev-v2.7/ckan/lib/cli.py#L185

Basically, this breaks the extension in CKAN 2.7.

**Comment by Zharktas** [comment]
This was fixed in https://github.com/ckan/ckanext-archiver/commit/3913e640f8604f1bdd5664593fa4a91da5624b32
