### ISSUE TITLE
Maintainer needed!

### ISSUE THREAD

**Issue by davidread** [ckan/ckanext-archiver#62]
I'm not been involved in ckanext-archiver for a while. There are a few outstanding issues - nothing big - some query about celery. I wonder if anyone who is actually using this CKAN extension is willing to take on a small responsibility for it, have a look at and tend to it going forward?

@Zharktas @thenets @KrzysztofMadejski

**Comment by Zharktas** [comment]
We still use archiver in multiple projects and our client Population Register Centre of Finland is willing that we use our billable time to contribute to upstream projects. So I can maintain it at least for the next year. At least I can get my PR's accepted ;)

**Comment by davidread** [comment]
Thankyou @Zharktas! I've added you as admin and leave it in your capable hands.
