### ISSUE TITLE
Howto start the two paster commands for celery in background

### ISSUE THREAD

**Issue by cesarjorgemartinez** [ckan/ckanext-archiver#66]
Hi,

I try to install this ckanext extension in CentOS 7.6. Then, the command line to start the celery processes launch the process as foreground. Exist options to start these processes as background/daemon, and use with monit yum package?

Regards

**Comment by Zharktas** [comment]
https://github.com/ckan/ckanext-archiver#using-archiver "For production use, we recommend setting up Celery to run with supervisord. apt-get install supervisor and use bin/celery-supervisor.conf as a configuration template.

If you are running CKAN 2.7 or higher, configure job workers instead http://docs.ckan.org/en/2.8/maintaining/background-tasks.html#using-supervisor"
