### ISSUE TITLE
Headers is not JSON serializable

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckanext-archiver#9]
In https://github.com/ckan/ckanext-archiver/blob/master/ckanext/archiver/tasks.py#L365
`return json.dumps(headers)`

throws `{blabla} is not JSON serializable`

headers is instance of `CaseInsensitiveDict`

Changing this line to: `json.dumps(dict(headers))`  resolve this issue.

**Comment by davidread** [comment]
Thanks @KrzysztofMadejski - looks like you have a newer version of 'requests' which caused this. Now fixed.
